### PR TITLE
Release v0.5

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
/cc @abonander

### CODE REVIEW

**Review by Darksonn — APPROVED** [review]

**Comment by Darksonn** [comment]
Btw, you might want to add semver checking to CI like we recently did for Tokio.

**Comment by Thomasdezeeuw** [comment]
> Btw, you might want to add semver checking to CI like we recently did for Tokio.

You mean https://github.com/tokio-rs/tokio/blob/ca9f7ee9f4750d6bb8a073ab4df1b7e4555857ad/.github/workflows/ci.yml#L233-L248 and https://github.com/obi1kenobi/cargo-semver-checks?

**Comment by Darksonn** [comment]
Yes.

**Comment by Thomasdezeeuw** [comment]
Created https://github.com/rust-lang/socket2/issues/396 for it.

**Comment by Thomasdezeeuw** [comment]
Thanks for the reviews @Darksonn

**Comment by cgwalters** [comment]
FWIW, this semver bump is causing a ripple effect https://github.com/bytecodealliance/cap-std/commit/963eebf3ab52b04a2e8b9ba88ce6308bbed5cbd0#r121651362

Not saying it was wrong to do...but I just want to ensure the cost/benefit is more visible.

**Comment by Thomasdezeeuw** [comment]
> FWIW, this semver bump is causing a ripple effect [bytecodealliance/cap-std@963eebf#r121651362](https://github.com/bytecodealliance/cap-std/commit/963eebf3ab52b04a2e8b9ba88ce6308bbed5cbd0#r121651362)
> 
> Not saying it was wrong to do...but I just want to ensure the cost/benefit is more visible.

I'm aware of the cost. v0.5 was required mainly to resolve https://github.com/rust-lang/socket2/issues/218, which showed that some of the API in v0.4 is unsound (it can use an arbitrary integer as fd without `unsafe`). Furthermore v0.4 is still supported, so if the unsound API is not used (incorrect) crates have plenty of time to update to v0.5.

Updating a heavily used crate in a breaking way is a pain, I'm aware, but at times it's required. v0.5 was the second breaking change in roughly the same amount of years. I try to keep a detailed changelog: https://github.com/rust-lang/socket2/blob/master/CHANGELOG.md#050 with clearly indicated API breakage and upgrade path. In other words I try to make the update experience as painless as possible.

All that said, updating existing, working code for little (perceived) benefit is always an annoying experience, just know that I'm not doing it annoy people.

**Pull request merged**
