### PR TITLE
Add support for QNX Neutrino to `master` branch

### PR DESCRIPTION
**Pull request by flba-eb**
CC @gh-tr

### CODE REVIEW

**Comment by flba-eb** [comment]
Clippy issues should vanish with #365.

**Review by Thomasdezeeuw — APPROVED** [review]
LGTM.

Any way to setup CI? Even running `cargo check` is good enough.

**Comment by flba-eb** [comment]
> LGTM.
> 
> Any way to setup CI? Even running `cargo check` is good enough.

I'm afraid this is not yet possible because of the missing standard library: https://github.com/rust-lang/rust/pull/106673
This will take some months to arrive in stable.

**Comment by Thomasdezeeuw** [comment]
> I'm afraid this is not yet possible because of the missing standard library: [rust-lang/rust#106673](https://github.com/rust-lang/rust/pull/106673) This will take some months to arrive in stable.

We used have Redox on a nightly-only CI, so if that's possible it's fine to. In the mean time I'll merge this.

**Comment by flba-eb** [comment]
Thank you very much, @Thomasdezeeuw . I would appreciate if you would also merge it to the `0.4` branch.

**Comment by Thomasdezeeuw** [comment]
Done in https://github.com/rust-lang/socket2/pull/382.

**Pull request merged**
