### PR TITLE
Add links to OS documentation, attempt 3

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
Replaces #248.

This increases MSRV to 1.54 (released nearly a year ago).

### CODE REVIEW

**Comment by Darksonn** [comment]
I notice that you have an open tracking issue for a breaking release. Is the MSRV bump happening as part of a breaking release?

**Comment by carllerche** [comment]
Socket2 bumping MSRV as an 0.x.0 release would be fine for us downstream (Tokio), but Tokio needs at a minimum 1.49.0 for socket2 0.4.x

**Comment by Thomasdezeeuw** [comment]
> I notice that you have an open tracking issue for a breaking release. Is the MSRV bump happening as part of a breaking release?

It's a year old so I figure it's ok, but we can bump to 0.5.x.

> Socket2 bumping MSRV as an 0.x.0 release would be fine for us downstream (Tokio), but Tokio needs at a minimum 1.49.0 for socket2 0.4.x

I though Tokio supported 6 months of Rust versions. Is this for a LTS release?

**Comment by carllerche** [comment]
@Thomasdezeeuw yes, but we also don't break MSRV in patch releases. If `socket2` breaks MSRV in a patch it will break at the very least our LTS which is pinned.

**Comment by Thomasdezeeuw** [comment]
I'll start the v0.5.x version and update rustc to 1.62 (has creation of `unix::SocketAddr`) or something.

**Comment by Thomasdezeeuw** [comment]
Created https://github.com/rust-lang/socket2/pull/320 for v0.5, I've updated the MSRV to 1.62, aiming to support 1.63 (for I/O safety).

**Pull request merged**
