### PR TITLE
Ipv6 incl hop limit

### PR DESCRIPTION
**Pull request by andreybuchinskiy**
Adding support for enabling IPV6_RECVHOPLIMIT on sockets for Linux OS

### CODE REVIEW

**Comment by andreybuchinskiy** [comment]
Clippy is failing, but it is also failing on master. I can make the required changes to make Clippy happy if necessary.

**Review by Thomasdezeeuw — CHANGES_REQUESTED** [review]

**Review by Thomasdezeeuw — APPROVED** [review]
Forgot to ask last time, can you add a test? A basic set & get should be sufficient, see `tests/socket.rs`.

**Comment by Thomasdezeeuw** [comment]
Thanks @andreybuchinskiy

**Comment by reneleonhardt** [comment]
Hello @Thomasdezeeuw can you add a changelog entry for 0.5.9?

**Comment by Thomasdezeeuw** [comment]
> Hello @Thomasdezeeuw can you add a changelog entry to 0.5.9?

This was merged into the 0.6 branch (current master)

**Comment by reneleonhardt** [comment]
> > Hello @Thomasdezeeuw can you add a changelog entry to 0.5.9?
> 
> This was merged into the 0.6 branch (current master)

GitHub shows that this commit is contained in master:
https://github.com/rust-lang/socket2/commits/v0.5.x/
https://github.com/rust-lang/socket2/commit/56e625efa4c85157636027823af1b1cc84e758f6

IntelliJ shows that this commit is contained in v0.5.x and master 🙈

When I run `cargo package` these changes are part of the source artifact... so my best guess still is that they are contained in 0.5.9 😄

Can you update the Branches section in the README to reflect the current release and development branches?

**Pull request merged**
