### PR TITLE
Haiku: fix build as IP_RECVTOS does not exist (v0.4.x)

### PR DESCRIPTION
**Pull request by nielx**
This is a backport of https://github.com/rust-lang/socket2/pull/369 / commit https://github.com/rust-lang/socket2/commit/ed233839be976d07f463ac3eb4dc0d6e19e333ab

### CODE REVIEW

**Review by Thomasdezeeuw — APPROVED** [review]

**Comment by nielx** [comment]
@Thomasdezeeuw Could this change be reconsidered? We are about a year later and despite all attempts, the 0.4.x branch does not want to seem to die. I have cherry-picked the patch on the latest commit in the 0.4.x branch, and it still applies (and builds).

**Comment by Thomasdezeeuw** [comment]
It was never about not accepting the change. But our policy is to apply it to main first and only then backport it. Otherwise patches and fixes become undone between versions.

**Comment by nielx** [comment]
I parsed the original rejection comment differently.

In any case, the changes are on main (as part of ed233839be976d07f463ac3eb4dc0d6e19e333ab), so this retroactively is a backport now.

**Comment by Thomasdezeeuw** [comment]
> I parsed the original rejection comment differently.

That's too bad about the miscommunication.

> In any case, the changes are on main (as part of [ed23383](https://github.com/rust-lang/socket2/commit/ed233839be976d07f463ac3eb4dc0d6e19e333ab)), so this retroactively is a backport now.

Can you update the commit saying it's a backport of that commit? That way I can keep track of everything.

**Comment by nielx** [comment]
Commit rebased, commit message and PR description updated.

**Comment by Thomasdezeeuw** [comment]
Thanks @nielx

**Pull request merged**
