### PR TITLE
haiku: Fix consumers by removing unsupported TOS calls

### PR DESCRIPTION
**Pull request by kallisti5**

### CODE REVIEW

**Comment by kallisti5** [comment]
doing this in hopes of an eventual 0.4.11 :-)     A lot of stuff depends on socket2 0.4.10 which breaks a lot of crates on Haiku

**Comment by kallisti5** [comment]
note: Targeting 0.4.x here.  If there are no plans for any more 0.4.x version releases, please ignore and close.

**Comment by Thomasdezeeuw** [comment]
Is this already in v0.5? If not please target that and I'll backport.

**Comment by kallisti5** [comment]
Ok.  These are all in 0.5.  :+1:

**Comment by Thomasdezeeuw** [comment]
It's fine to go in to v0.4, I just want to make sure we're not losing attributes going from v0.4 to v0.5.

**Pull request closed without merging**
