### PR TITLE
Add support for type-of-service option

### PR DESCRIPTION
**Pull request by aym-v**
Some network applications depend on proper marking of outgoing packets with ToS/DSCP fields. Routing protocols, management traffic, VoIP applications, etc., all depend on the ToS field.

ToS can be set at the socket level using the setsockopt call, using the IPPROTO_IP level and the IP_TOS option. There is already `ttl` and `set_ttl `methods to get and set the TTL field. 

This PR adds a `tos` and `set_tos `methods.

### CODE REVIEW

**Review by Thomasdezeeuw — APPROVED** [review]
LGTM.

The first sentence of the Windows documentation does say "Do not use." (https://docs.microsoft.com/en-us/windows/win32/winsock/ipproto-ip-socket-options, search for IP_TOS). Maybe we should echo that in the docs?

**Comment by aym-v** [comment]
Indeed, I added a disclaimer linking to the Windows doc. 
Related: https://github.com/golang/go/issues/42728

**Review by Thomasdezeeuw — APPROVED** [review]

**Comment by aym-v** [comment]
Since not all target OSes support `IP_TOS`, I will add a commit to conditionally enable the option

**Review by Thomasdezeeuw — APPROVED** [review]

**Comment by Thomasdezeeuw** [comment]
@aym-v do you have time to update this? I could take over if not.

**Comment by aym-v** [comment]
@Thomasdezeeuw I was not able to reproduce the CI failures on my local computer by using the same commands. That's weird

**Comment by Thomasdezeeuw** [comment]
@aym-v did you rebase on master? `git fetch origin && git rebase origin/master`, assuming `origin` points to this repo.

**Comment by aym-v** [comment]
@Thomasdezeeuw Indeed, I did not do it. I just rebased the branch on master and updated the failing parts.

**Comment by Thomasdezeeuw** [comment]
Fuchsia doesn't seem to have `libc::IP_TOS` defined. It could be that Fuchsia doesn't define/support the constant, or that the `libc` crate simply doesn't have it (yet). If you want, you can add it to the `libc` crate, but I would be ok with dropping Fuchsia support from this change as well, then we can open an issue for it and do it later, up to you @aym-v.

**Comment by aym-v** [comment]
Fortunately, fuschia supports these constants, I just opened a PR on libc to expose them!

**Comment by Thomasdezeeuw** [comment]
Thanks @aym-v! I didn't release the libc pr was merged some time ago.

**Pull request merged**
