### PR TITLE
Support AIX operating system

### PR DESCRIPTION
**Pull request by ecnelises**

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
LGTM in principle, although I won't be able to officially support it. Two questions:
 * Can you resolve the merge conflicts?
 * Would it possible to create manual links for this by adding to `man_links`, see https://github.com/rust-lang/socket2/blob/4c436818cddec880c26c4e79aca7106ba88827ff/src/lib.rs#L120-L166?

**Comment by Thomasdezeeuw** [comment]
@ecnelises what is the status of this?

**Comment by ecnelises** [comment]
Hi, the code part is ready. But AIX doesn't have a universal online man page url. For example, https://www.ibm.com/docs/en/aix/7.3?topic=f-fcntl-dup-dup2-subroutine or https://www.ibm.com/docs/en/aix/7.3?topic=i-iconv-subroutine

**Review by Thomasdezeeuw — APPROVED** [review]
LGTM. Three questions:
* Can you rebase on master, we have added some code since this was originally written, so it might not build after a rebase.
* Can you fix the rustfmt error.
* Is their anything we can do for CI? Even a `cargo check` would be a good start.

**Comment by ecnelises** [comment]
Thanks @Thomasdezeeuw 

For `cargo check`, since `powerpc64-ibm-aix` is not fully available through rustup, it would fail. I will add it to `cargo check` matrix after it's available. :)

**Comment by Thomasdezeeuw** [comment]
Do you want to merge this now @ecnelises or do you want to wait until we have some CI support?

**Comment by ecnelises** [comment]
Thanks, I'd like to merge it now.

**Comment by Thomasdezeeuw** [comment]
Thanks @ecnelises

**Pull request merged**
