### PR TITLE
Backport ESP-IDF support from main branch

### PR DESCRIPTION
**Pull request by jasta**
Same changes and test case as #452.

### CODE REVIEW

**Comment by jasta** [comment]
v0.4.x support is required right now because tokio is currently using 0.4.9 and presumably would have an easier time updating to 0.4.10.

**Comment by jasta** [comment]
CI fails look unrelated to me...

**Review by Thomasdezeeuw — APPROVED** [review]

**Comment by Thomasdezeeuw** [comment]
Fixing the CI in https://github.com/rust-lang/socket2/pull/457.

**Comment by Thomasdezeeuw** [comment]
Thanks @jasta

**Pull request merged**
