### PR TITLE
Release v0.5.3

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**

### CODE REVIEW

**Review by Darksonn — APPROVED** [review]

**Comment by Thomasdezeeuw** [comment]
That was a fast review, thanks @Darksonn

**Comment by Thomasdezeeuw** [comment]
Release is also done.

**Comment by Darksonn** [comment]
Yeah, I just happened to see the email right when you sent it.

**Comment by dignifiedquire** [comment]
Wow, that was fast! thanks a lot

**Pull request merged**
