### PR TITLE
Fuchsia doesn't support sendfile

### PR DESCRIPTION
**Pull request by erickt**
Fuchsia doesn't support `sendfile`.

edit: previously I asked for a point release with this because of the typo in "fuchsia", but we don't actually need it since this was for an unsupported syscall.

### CODE REVIEW

**Comment by tamird** [comment]
Looks like some of this fails to compile; we should just remove those parts.

```
error[E0425]: cannot find function `sendfile` in crate `libc`
    --> src/sys/unix.rs:1384:18
     |
1384 |         syscall!(sendfile(self.inner, file, &mut offset, count)).map(|n| n as usize)
     |                  ^^^^^^^^ not found in `libc`

error[E0425]: cannot find function `sendfile` in crate `libc`
    --> src/sys/unix.rs:1384:18
     |
1384 |         syscall!(sendfile(self.inner, file, &mut offset, count)).map(|n| n as usize)
     |                  ^^^^^^^^ not found in `libc`
```

**Comment by erickt** [comment]
Turns out fuchsia doesn't support `sendfile`. I just removed these lines instead.

**Review by Thomasdezeeuw — APPROVED** [review]

**Comment by Thomasdezeeuw** [comment]
@erickt can you run rustfmt on this, then I think it's good to go.

**Comment by Thomasdezeeuw** [comment]
Thanks @erickt

**Pull request merged**
